name: Update Naukri Resume

on:
  schedule:
    - cron: '0 0 * * 1,4' # Run every Monday and Thursday
  # Add this to make it easier to trigger manually
  workflow_dispatch:

jobs:
  upload-resume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload resume to Naukri
        uses: ./
        with:
          username: ${{ secrets.NAUKRI_USERNAME }}
          password: ${{ secrets.NAUKRI_PASSWORD }}
          profile_id: ${{ secrets.NAUKRI_PROFILE_ID }}
          resume_path: |-
            resumes/resume1.pdf
